package gatech;

import java.io.Serializable;
import java.util.LinkedHashMap;


public class Studio implements Serializable{
    private String studioShortName;
    private String studioLongName;
    private int studioCurrentRevenue;
    private int studioPreviousRevenue;
    private int studioTotalRevenue;
    private LinkedHashMap<String, Integer> studioRevenueHistory;

    // Because Event class contains Studio's info, I don't need to store events that generated by studio here
    public Studio(String studioShortName, String studioLongName){
        this.studioShortName = studioShortName;
        this.studioLongName = studioLongName;
        this.studioCurrentRevenue = 0;
        this.studioPreviousRevenue = 0;
        this.studioTotalRevenue = 0;
        this.studioRevenueHistory = new LinkedHashMap<String, Integer>();

    }

    public Object[][] display_studio(){
        System.out.println("studio," + studioShortName + "," + studioLongName);
        System.out.println("current_period," + studioCurrentRevenue);
        System.out.println("previous_period," + studioPreviousRevenue);
        System.out.println("total," + studioTotalRevenue);
        Object[][] result ={{"studio," , studioShortName + "," + studioLongName},{"current_period," , studioCurrentRevenue},
                {"previous_period,", studioPreviousRevenue},{"total,", studioTotalRevenue}};
        return result;
    }

    public void get_licensing_paid(Event event){
        studioCurrentRevenue += event.get_event_licensefee();
    }

    public String get_shortname(){
        return studioShortName;
    }

    public void next_month() {
        studioTotalRevenue += studioCurrentRevenue;
        studioPreviousRevenue = studioCurrentRevenue;
        String currDate = TestCaseReader.getMonthTimeStamp() + "/" + TestCaseReader.getYearTimeStamp();
        studioRevenueHistory.put(currDate, studioCurrentRevenue);

        studioCurrentRevenue = 0;
    }

    public LinkedHashMap<String, Integer> getStudioRevenueHistory() {
        return studioRevenueHistory;
    }
}
